/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jacekkowalczyk82.docx.tools;

import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFTable;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;

public class AddSolidBordersApp {


    public static void main(String[] args) {
        if (args.length == 0) {
            usage();
        }
        else {
            System.out.println("Addding Solid Borders to tables ");

            try {
                String inputFileName = args[0];
                XWPFDocument document= new XWPFDocument(new FileInputStream(inputFileName));
                for (XWPFTable table : document.getTables()) {
                    table.setWidth("100%");

                    //set borders
                    table.setTopBorder(XWPFTable.XWPFBorderType.SINGLE, 1, 0, "000000");
                    table.setBottomBorder(XWPFTable.XWPFBorderType.SINGLE, 1, 0, "000000");
                    table.setLeftBorder(XWPFTable.XWPFBorderType.SINGLE, 1, 0, "000000");
                    table.setRightBorder(XWPFTable.XWPFBorderType.SINGLE, 1, 0, "000000");
                    table.setInsideHBorder(XWPFTable.XWPFBorderType.SINGLE, 1, 0, "000000");
                    table.setInsideVBorder(XWPFTable.XWPFBorderType.SINGLE, 1, 0, "000000");



                }
                FileOutputStream fileOut = new FileOutputStream(inputFileName+ "_fixed_solidborders.docx");
                document.write(fileOut);
                fileOut.close();
                document.close();



            } catch (IOException e) {
                throw new RuntimeException(e);
            }

        }

    }

    public static void usage() {
        System.out.println("Addding Solid Borders to tables ");
        System.out.println("Required parameters were not provided");
        System.out.println("Usage: solidtableborders.bat <PATH TO INPUT DOCX FILE>");
    }
}
