/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jacekkowalczyk82.docx.tools;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        AddSolidBordersApp classUnderTest = new AddSolidBordersApp();
        assertNotNull(classUnderTest);
    }
}
